In [ ]:
# Project 2 - Yelp API

In [ ]:
# !pip install yelpapi

In [1]:
# Dependencies and Setup
import requests
import json
import pandas as pd

# Import API key
from api_keys import api_key

In [2]:
api_key='QWMy8-jFwxoKJkLNvzLl-jDymYjp-bN83izdcDMb91a3JG5h_8XRcjYNWWSXYhKjo0cPdnC_UdrnlAaap6kwUqa3Cqm2dCU202lvbXL3AkUqJ_m7PQAFKlqnvmGyXHYx'

headers = {'Authorization': 'Bearer %s' % api_key}

In [3]:
url='https://api.yelp.com/v3/businesses/search'

# 1) Toronto

In [4]:
# Perform API Calls - test with one restaurant 

params_to = {'term':'restaurant',
     'location':'Toronto', 
     'sort_by': 'rating',        
     'limit':'50'}

In [5]:
request=requests.get(url, params=params_to, headers=headers)
print('The status code is {}'.format(request.status_code))

The status code is 200

In [6]:
#Convert the data into a JSON object
parsed_to = json.loads(request.text)
toronto = parsed_to["businesses"]

In [7]:
#“businesses” is a list, enclosed by a square brackets.
# extract businesses first into a Python list and then loop over the businesses in the list.
# count = 1
name = []
phone_number = []
postal_code =[]
address = []
city = []
rating = []
category = []
cost = []
review_count = []
 

for business in toronto:
    #print("Number:", count)
    #print("Name:", business["name"])
    #print("Address:", " ".join(business["location"]["display_address"]))
    #print("City:", " ".join(business["location"]["city"]))
    #print("Rating:", business["rating"])
    #print("Category:", business["categories"][0].get('alias'))
        
    #if 'price' in business:
    #    print("Cost:", business["price"])
    #
    #print("\n")
    #print("Review Count:", business["review_count"])
    
    name.append(business["name"])
    phone_number.append(business["phone"])        
    postal_code.append(business["location"]["zip_code"])
    address.append(business["location"]["display_address"])
    city.append(business["location"]["city"])
    rating.append(business["rating"])
    category.append(business["categories"][0].get('alias'))
    
    
    if 'price' in business:
        cost.append(business["price"])
    else:
        cost.append("")
    review_count.append(business["review_count"])

    # count = count+1

In [8]:
#Display the DataFrame

#Display the DataFrame
df_to = pd.DataFrame(data={"name": name, "phone_number": phone_number,"postal_code": postal_code, "address": address, "city": city, "rating":
                       rating, "category": category, "cost": cost, "review_Count": review_count})

df_sort_to = df_to.sort_values(by=['rating'], ascending=False)
df_sort_to

,name,phone_number,postal_code,address,city,rating,category,cost,review_Count
0,Baretto Caffe,+14163850003,M3B 2W7,"[1262 Don Mills Road, Toronto, ON M3B 2W7, Can...",Toronto,5.0,cafes,$,293
4,Veghed,+14168416673,M6J 1X3,"[1199 Dundas Street W, Toronto, ON M6J 1X3, Ca...",Toronto,5.0,vegan,$$,60
45,Momo Hut & Gardens,+14163638580,M4K 1P1,"[401 Danforth Avenue, Danforth, Toronto, ON M4...",Toronto,5.0,himalayan,,41
38,I'll Be Seeing You,+14167789988,M4M 1H3,"[747 Queen Street E, Toronto, ON M4M 1H3, Canada]",Toronto,5.0,cocktailbars,$$,39
35,Ravi Soups,+16474358365,M5V 1R1,"[322 Adelaide Street W, Toronto, ON M5V 1R1, C...",Toronto,4.5,sandwiches,$$,343
27,Sugo,+14165351717,M6H 3Y2,"[1279 Bloor Street W, Toronto, ON M6H 3Y2, Ca...",Toronto,4.5,italian,$$,96
28,Riddle Room,+16473442637,M4Y 1Z2,"[579 Yonge Street, 2nd Floor, Toronto, ON M4Y ...",Toronto,4.5,cafes,$,161
29,Beach Hill Smokehouse,+14167928275,M4E 2W1,"[172 Main Street S, Toronto, ON M4E 2W1, Canada]",Toronto,4.5,bbq,$$,73
30,Takht-e Tavoos,+16473527322,M6H 1B5,"[1120 College Street, Toronto, ON M6H 1B5, Can...",Toronto,4.5,persian,$$,120
31,Rasa,+16473508221,M5S 2K8,"[196 Robert Street, Toronto, ON M5S 2K8, Canada]",Toronto,4.5,newcanadian,$$,226
32,Saigon Lotus,+14169011115,M5T 1K6,"[6 St Andrew Street, Toronto, ON M5T 1K6, Canada]",Toronto,4.5,vietnamese,$$,151
33,Veggie D'Light,+16473527581,M5T 3K7,"[160 Baldwin Street, Unit 3, Toronto, ON M5T 3...",Toronto,4.5,caribbean,$,62
34,Salus Fresh Foods,+14165931515,M5B 1L4,"[25 Carlton Street, Unit D, Toronto, ON M5B 1L...",Toronto,4.5,salad,$,55
37,Black Camel,+14169297518,M4W 1S9,"[4 Crescent Road, Toronto, ON M4W 1S9, Canada]",Toronto,4.5,sandwiches,$,324
36,Le Baratin,+14165348800,M6K 1T8,"[1600 Dundas Street. W, Toronto, ON M6K 1T8, C...",Toronto,4.5,french,$$,85
1,Yasu,+14164772361,M5S,"[81 Harbord Street, Toronto, ON M5S, Canada]",Toronto,4.5,japanese,$$$$,328
39,Loga's Corner,+16477610965,M6K 2V5,"[216C Close Avenue, Toronto, ON M6K 2V5, Canada]",Toronto,4.5,himalayan,$,99
41,The Olde Yorke,+14166969670,M4G 3V3,"[96 Laird Drive, East York, ON M4G 3V3, Canada]",East York,4.5,seafood,$$,231
42,Pow Wow Cafe,+14165517717,M5T 2L4,"[213 Augusta Avenue, Toronto, ON M5T 2L4, Canada]",Toronto,4.5,newcanadian,$$,102
43,COO Café Bread or Rice,+16473515166,M6H 1M4,"[1049 Bloor Street W, Toronto, ON M6H 1M4, Can...",Toronto,4.5,japanese,$$,68
46,Rustle & Still Café,+16473508893,M6G 1K6,"[605 Bloor Street W, Toronto, ON M6G 1K6, Canada]",Toronto,4.5,coffee,$,79
47,Nuit Social,+16473506848,M6J 1J5,"[1168 Queen Street W, Toronto, ON M6J 1J5, Can...",Toronto,4.5,cocktailbars,$$,194
48,George,+14168636006,M5C 1S2,"[111 Queen Street E, Toronto, ON M5C 1S2, Canada]",Toronto,4.5,newcanadian,$$$$,246
26,Katsuya,+14165917756,M5B 2M2,"[66 Gerrard Street E, Unit 100, Toronto, ON M5...",Toronto,4.5,japanese,$$,315
25,Crepe TO,+16473525286,M5C 3C8,"[52 Church Street, Toronto, ON M5C 3C8, Canada]",Toronto,4.5,creperies,$$,73
24,Tibet Kitchen,+14169138726,M6R 1A6,"[1544 Queen Street W, Toronto, ON M6R 1A6, Can...",Toronto,4.5,himalayan,$$,234
13,Her Father's Cider Bar & Kitchen,+16473477747,M5S 1G7,"[119 Harbord Street, Toronto, ON M5S 1G7, Canada]",Toronto,4.5,gastropubs,$$,132
2,Alo Restaurant,+14162602222,M5V 2A5,"[163 Spadina Avenue, 3rd Floor, Toronto, ON M5...",Toronto,4.5,bars,$$$$,250
3,Blaze Fast-Fire'd Pizza,+16479331028,M5B 2G9,"[10 Dundas Street East, #124, Toronto, ON M5B ...",Toronto,4.5,pizza,$$,468
5,Jacobs & Co. Steakhouse,+14163660200,M5V 1K4,"[12 Brant Street, Toronto, ON M5V 1K4, Canada]",Toronto,4.5,steak,$$$$,508
6,El Nahual,+14164106012,M6M 3Y3,"[1993 Keele Street, York, ON M6M 3Y3, Canada]",York,4.5,mexican,$,99
7,Seven Lives Tacos Y Mariscos,+14163934636,M5T 2K2,"[69 Kensington Avenue, Toronto, ON M5T 2K2, Ca...",Toronto,4.5,mexican,$,1215
8,Richmond Station,+16477481444,M5H 3W4,"[1 Richmond Street W, Toronto, ON M5H 3W4, Can...",Toronto,4.5,newcanadian,$$$,676
9,Pai Northern Thai Kitchen,+14169014724,M5H 3G8,"[18 Duncan Street, Toronto, ON M5H 3G8, Canada]",Toronto,4.5,thai,$$,2362
10,Mystic Muffin,+14169411474,M5C 2H4,"[113 Jarvis Street, Toronto, ON M5C 2H4, Canada]",Toronto,4.5,sandwiches,$,249
11,Byblos,+16476600909,M5V 3M2,"[11 Duncan Street, Toronto, ON M5V 3M2, Canada]",Toronto,4.5,mediterranean,$$$,740
12,Scaramouche Restaurant Pasta Bar & Grill,+14169618011,M4V 2L1,"[1 Benvenuto Place, Toronto, ON M4V 2L1, Canada]",Toronto,4.5,french,$$$$,266
14,Antler Kitchen & Bar,+16473458300,M6J 1Y6,"[1454 Dundas Street West, Toronto, ON M6J 1Y6,...",Toronto,4.5,newcanadian,$$$,220
15,Adamson Barbecue,+16475592080,M4G 2B6,"[176 Wicksteed Avenue, Toronto, ON M4G 2B6, Ca...",Toronto,4.5,bbq,$$,232
16,Agio,+16473484814,M6E 1C5,"[1351 St Clair Avenue W, Toronto, ON M6E 1C5, ...",Toronto,4.5,italian,$$,161
17,Ramen Isshin,+14163674013,M5T 1T1,"[421 College Street, Toronto, ON M5T 1T1, Canada]",Toronto,4.5,ramen,$$,544
18,A-Game Cafe,+14169714263,M6J 1V2,"[797 Dundas Street W, Toronto, ON M6J 1V2, Can...",Toronto,4.5,cafes,$,89
19,Descendant Detroit Style Pizza,+16473471168,M4M 1L5,"[1168 Queen Street E, Toronto, ON M4M 1L5, Can...",Toronto,4.5,pizza,$$,274
20,Fresco's Fish & Chips,+14165464557,M5T 2L4,"[201 Augusta Avenue, Toronto, ON M5T 2L4, Canada]",Toronto,4.5,fishnchips,$$,327
21,Café Polonez,+14165328432,M6R 2L5,"[195 Roncesvalles Avenue, Toronto, ON M6R 2L5,...",Toronto,4.5,polish,$$,231
22,Schnitzel Queen,+14165041311,M5A 1S5,"[211 Queen Street E, Toronto, ON M5A 1S5, Canada]",Toronto,4.5,german,$$,87
49,Hodo Kwaja,+14165381208,M6G 1K9,"[656 Bloor Street W, Toronto, ON M6G 1K9, Canada]",Toronto,4.5,bakeries,$,197
23,Banh Mi Boys,+14163630588,M5V 2A9,"[392 Queen Street W, Toronto, ON M5V 2A9, Canada]",Toronto,4.0,sandwiches,$,1071
40,Miku,+16473477347,M5J 2R8,"[105-10 Bay Street, Toronto, ON M5J 2R8, Canada]",Toronto,4.0,japanese,$$$,673
44,KINKA IZAKAYA ORIGINAL,+14169770999,M5B 2A2,"[398 Church St, Toronto, ON M5B 2A2, Canada]",Toronto,4.0,japanese,$$,1492

In [9]:
#Save to a CSV all data retrieved
df_sort_to.to_csv("Toronto.csv", sep=',',index=False)
#df_to.to_csv("Toronto.csv", sep=',',index=False)

# 2) New York

In [10]:
# Perform API Calls - test with one restaurant 

params_ny = {'term':'restaurant',
     'location':'New York', 
     'sort_by': 'rating',        
     'limit':'50'}

In [11]:
request=requests.get(url, params=params_ny, headers=headers)
print('The status code is {}'.format(request.status_code))

The status code is 200

In [12]:
#Convert the data into a JSON object
parsed_ny = json.loads(request.text)
newyork = parsed_ny["businesses"]

In [13]:
#print parsed to get an idea how it looks like
#print(json.dumps(parsed_ny, indent=4))

In [14]:
#“businesses” is a list, enclosed by a square brackets.
# extract businesses first into a Python list and then loop over the businesses in the list.
# count = 1
name = []
phone_number = []
postal_code =[]
address = []
city = []
rating = []
category = []
cost = []
review_count = []
 

for business in newyork:
    #print("Number:", count)
    #print("Name:", business["name"])
    #print("Address:", " ".join(business["location"]["display_address"]))
    #print("City:", " ".join(business["location"]["city"]))
    #print("Rating:", business["rating"])
    #print("Category:", business["categories"][0].get('alias'))
        
    #if 'price' in business:
    #    print("Cost:", business["price"])
    #
    #print("\n")
    #print("Review Count:", business["review_count"])
    
    name.append(business["name"])
    phone_number.append(business["phone"])        
    postal_code.append(business["location"]["zip_code"])
    address.append(business["location"]["display_address"])
    city.append(business["location"]["city"])
    rating.append(business["rating"])
    category.append(business["categories"][0].get('alias'))
    
    
    if 'price' in business:
        cost.append(business["price"])
    else:
        cost.append("")
    review_count.append(business["review_count"])

    # count = count+1

In [15]:
#Display the DataFrame
df_ny = pd.DataFrame(data={"name": name, "phone_number": phone_number,"postal_code": postal_code, "address": address, "city": city, "rating":
                       rating, "category": category, "cost": cost, "review_Count": review_count})

df_sort_ny = df_ny.sort_values(by=['rating'], ascending=False)
df_sort_ny

,name,phone_number,postal_code,address,city,rating,category,cost,review_Count
0,Otis,+16468860601,11206,"[18 Harrison Pl, Brooklyn, NY 11206]",Brooklyn,5.0,newamerican,$$,172
17,Pita Palace,+17183830550,11211,"[413 Graham Ave, Brooklyn, NY 11211]",Brooklyn,5.0,mideastern,$,210
38,Kafe Louverture,+13473053176,11216,"[392 Halsey St, Brooklyn, NY 11216]",Brooklyn,5.0,coffee,$,97
33,4 Charles Prime Rib,+12125615992,10014,"[4 Charles St, New York, NY 10014]",New York,5.0,steak,$$$,194
41,Panzerotti Bites,+17184889300,11231,"[235 Smith St, Brooklyn, NY 11231]",Brooklyn,5.0,italian,$$,80
42,Dian Kitchen,+16465909898,10009,"[435 E 9th St, New York, NY 10009]",New York,5.0,chinese,$$,132
28,191 Knickerbocker,+19293053625,11237,"[191 Knickerbocker Ave, Brooklyn, NY 11237]",Brooklyn,5.0,breakfast_brunch,$$,82
43,Three Seat Espresso,+19173882769,10009,"[137 Avenue A, New York, NY 10009]",New York,5.0,coffee,$$,178
26,Sushi Lin,+13476276027,11217,"[335 Flatbush Ave, Brooklyn, NY 11217]",Brooklyn,5.0,sushi,$$$,206
1,The Alcove,+13478134159,11104,"[41-11 49th St, Sunnyside, NY 11104]",Sunnyside,5.0,gastropubs,$$,677
24,Lella Alimentari,+17185992625,11211,"[325 Manhattan Ave, Brooklyn, NY 11211]",Brooklyn,5.0,coffee,$,160
23,Second Street Bakery,+12014201793,07302,"[402 2nd St, Jersey City, NJ 07302]",Jersey City,5.0,bakeries,$,184
45,Lillo Cucina Italiana,+13477630899,11201,"[331 Henry St, Brooklyn, NY 11201]",Brooklyn,5.0,cafes,$,75
20,Frenchy's Food Truck,+16464682861,11238,"[341 Eastern Pkwy, Brooklyn, NY 11238]",Brooklyn,5.0,coffee,$,60
19,Tony's Beechhurst Deli,+17187678222,11357,"[1118 154th St, Whitestone, NY 11357]",Whitestone,5.0,delis,$$,153
36,Tres Leches Cafe,+16465590176,10029,"[356 E 112th St, New York, NY 10029]",New York,5.0,bakeries,$,94
18,Samurai Sushi,+12018961760,07073,"[254 Park Ave, East Rutherford, NJ 07073]",East Rutherford,5.0,japanese,$$,148
8,Miscelanea NY,+12122530277,10003,"[63 E 4th St, New York, NY 10003]",New York,5.0,coffee,$$,339
15,Non Solo Piada,+12122160616,10018,"[302 W 37th St, New York, NY 10018]",New York,5.0,italian,$$,275
2,Taste of Heaven,+17185763146,11211,"[251 Jackson St, Brooklyn, NY 11211]",Brooklyn,5.0,soulfood,$$,100
3,Korai Kitchen,+12017216566,07306,"[576 Summit Ave, Jersey City, NJ 07306]",Jersey City,5.0,bangladeshi,$$,174
4,Andrea Salumeria,+12016531666,07307,"[247 Central Ave, Apt 3, Jersey City, NJ 07307]",Jersey City,5.0,delis,$,232
5,L'industrie Pizzeria,+17185990002,11211,"[254 S 2nd St, Brooklyn, NY 11211]",Brooklyn,5.0,pizza,$,407
48,Joe's Italian Deli,+17183677979,10458,"[685 E 187th St, Bronx, NY 10458]",Bronx,5.0,delis,$$,98
7,Royal Grill Halal Food,+13477240504,10036,"[44th St And 6th Ave, New York, NY 10036]",New York,5.0,halal,$,252
37,Griot Cafe,+12014209444,07307,"[434 Central Ave, Jersey City, NJ 07307]",Jersey City,5.0,coffee,$$,94
9,Hold Fast Kitchen and Spirits,+19172616691,10036,"[364 W46th St, New York, NY 10036]",New York,5.0,cocktailbars,$$,157
10,Green Juice Cafe,+16469187730,10033,"[4316 Broadway, New York, NY 10033]",New York,5.0,sandwiches,$,165
11,Joey Bats Café,+12129511189,10002,"[129 Allen St, New York, NY 10002]",New York,5.0,desserts,$,146
12,Cafe Talya,+12015355333,07002,"[218 Ave B, Bayonne, NJ 07002]",Bayonne,5.0,cafes,$,222
14,Koroni Souvlaki and Grill,+17184898820,11102,"[29-37 Newtown Ave, Astoria, NY 11102]",Astoria,5.0,mediterranean,$$,206
44,Loi Estiatorio,+12127130015,10019,"[132 W 58th St, New York, NY 10019]",New York,4.5,greek,$$$,318
40,Sorriso Italian Pork Store,+17187284392,11103,"[4416 30th Ave, Astoria, NY 11103]",Astoria,4.5,meats,$,313
39,Mysttik Masaala,+19173063128,10022,"[399 Park Ave, Corner of 54th street, New York...",New York,4.5,foodtrucks,$,350
47,Top Thai Greenwich,+16467264418,10012,"[235 Sullivan St, New York, NY 10012]",New York,4.5,thai,$$,1069
46,Frisson Espresso,+16468503928,10036,"[326 W 47th St, New York, NY 10036]",New York,4.5,coffee,$,643
25,Casa d'Paco,+18623079466,07105,"[73 Warwick St, Newark, NJ 07105]",Newark,4.5,spanish,$$,534
35,Aux Merveilleux De Fred,+19174751992,10014,"[37 8th Ave, New York, NY 10014]",New York,4.5,desserts,$$,309
34,Laojie Hotpot,+17184310026,11220,"[811 53rd St, Brooklyn, NY 11220]",Brooklyn,4.5,hotpot,$$,436
32,Sami's Kabab House,+19178327165,11106,"[35-57 Crescent St, Astoria, NY 11106]",Astoria,4.5,afghani,$$,298
31,Jajaja,+16468835453,10002,"[162 E Broadway, New York, NY 10002]",New York,4.5,mexican,$$,640
30,Mughlai Grill,+12125332828,10002,"[6 Clinton St, New York, NY 10002]",New York,4.5,indpak,$$,277
29,Fiore Deli of Hoboken,+12016591655,07030,"[414 Adams St, Hoboken, NJ 07030]",Hoboken,4.5,delis,$,485
27,Los Mariscos,+12129204986,10011,"[409 W 15th St, New York, NY 10011]",New York,4.5,seafood,$,472
22,Sushi by Bou Times Square,,10036,"[132 W 47th St, New York, NY 10036]",New York,4.5,sushi,$$$,345
21,Baba's Pierogies,+17182220777,11215,"[295 3rd Ave, Brooklyn, NY 11215]",Brooklyn,4.5,modern_european,$$,350
16,"Sal, Kris, & Charlie's Deli",+17182789240,11105,"[33-12 23rd Ave, Astoria, NY 11105]",Astoria,4.5,delis,$,976
13,Los Tacos No.1,+12122560343,10011,"[75 9th Ave, New York, NY 10011]",New York,4.5,tacos,$,2634
6,Los Tacos No.1,+12125744696,10036,"[229 W 43rd St, New York, NY 10036]",New York,4.5,tacos,$,1098
49,Ruffian,,10009,"[125 E 7th St, New York, NY 10009]",New York,4.5,wine_bars,$$,186

In [16]:
#Save to a CSV all data retrieved
df_sort_ny.to_csv("NewYork.csv", sep=',',index=False)
#df_ny.to_csv("NewYork.csv", sep=',',index=False)

# 3) London

In [17]:
# Perform API Calls - test with one restaurant 
params_ld = {'term':'restaurant',
             'location':'London', 
             'sort_by': 'rating',    
             'limit':'50'}

In [18]:
request=requests.get(url, params=params_ld, headers=headers)
print('The status code is {}'.format(request.status_code))

The status code is 200

In [19]:
#Convert the data into a JSON object
parsed_ld = json.loads(request.text)
london = parsed_ld["businesses"]

In [20]:
#“businesses” is a list, enclosed by a square brackets.
# extract businesses first into a Python list and then loop over the businesses in the list.
# count = 1
name = []
phone_number = []
postal_code =[]
address = []
city = []
rating = []
category = []
cost = []
review_count = []
 

for business in london:
    #print("Number:", count)
    #print("Name:", business["name"])
    #print("Address:", " ".join(business["location"]["display_address"]))
    #print("City:", " ".join(business["location"]["city"]))
    #print("Rating:", business["rating"])
    #print("Category:", business["categories"][0].get('alias'))
        
    #if 'price' in business:
    #    print("Cost:", business["price"])
    #
    #print("\n")
    #print("Review Count:", business["review_count"])
    
    name.append(business["name"])
    phone_number.append(business["phone"])        
    postal_code.append(business["location"]["zip_code"])
    address.append(business["location"]["display_address"])
    city.append(business["location"]["city"])
    rating.append(business["rating"])
    category.append(business["categories"][0].get('alias'))
    
    
    if 'price' in business:
        cost.append(business["price"])
    else:
        cost.append("")
    review_count.append(business["review_count"])

    # count = count+1

In [21]:
#Display the DataFrame
#Display the DataFrame
df_ld = pd.DataFrame(data={"name": name, "phone_number": phone_number,"postal_code": postal_code, "address": address, "city": city, "rating":
                       rating, "category": category, "cost": cost, "review_Count": review_count})

df_sort_ld = df_ld.sort_values(by=['rating'], ascending=False)
df_sort_ld

,name,phone_number,postal_code,address,city,rating,category,cost,review_Count
0,The Golden Chippy,+442086924333,SE10 8LF,"[62 Greenwich High Road, Greenwich, London SE1...",London,5.0,fishnchips,££,67
4,Kennington Lane Cafe,+442077355853,SE11 5QY,"[383 Kennington Lane, Vauxhall, London SE11 5Q...",London,5.0,cafes,£,63
20,Il Portico,+442076026262,W8 6NA,"[277 Kensington High Street, London W8 6NA, Un...",London,5.0,italian,£££,48
16,Bageriet,+442072400000,WC2E 9EA,"[24 Rose Street, London WC2E 9EA, United Kingdom]",London,5.0,scandinavian,£,59
35,The Tiroler Hut Restaurant,+442077273981,W2 4UA,"[27 Westbourne Grove, London W2 4UA, United Ki...",London,4.5,german,££,67
27,The Fat Bear,+442072362498,EC4V 5DY,"[61 Carter Lane, London EC4V 5DY, United Kingdom]",London,4.5,tradamerican,££,107
28,Ozone Coffee,+442074901039,EC2A 4AQ,"[11 Leonard Street, London EC2A 4AQ, United Ki...",London,4.5,coffee,££,176
29,Barrafina,+442074401456,WC2N 4HZ,"[10 Adelaide Street, London WC2N 4HZ, United K...",London,4.5,spanish,£££,60
30,Pimlico Fresh,+442079320030,SW1V 1DE,"[85 Wilton Road, London SW1V 1DE, United Kingdom]",London,4.5,coffee,££,142
31,Quilon Restaurant,+442078211899,SW1E 6AF,"[41 Buckingham Gate, London SW1E 6AF, United K...",London,4.5,indpak,£££,143
32,Franco Manca,+442077383021,SW9 8LD,"[4 Market Row, Electric Lane, London SW9 8LD, ...",London,4.5,italian,£,168
33,Goodman,+442074993776,W1S 1QH,"[26 Maddox Street, London W1S 1QH, United King...",London,4.5,steak,£££,104
34,Kanada-Ya,+442072400232,WC2H 8LE,"[64 St Giles High Street, London WC2H 8LE, Uni...",London,4.5,ramen,££,141
36,Blacklock,+442034416996,W1D 7LG,"[The Basement, 24 Great Windmill Street, Londo...",London,4.5,british,£££,79
1,Ffiona's Restaurant,+442079374152,W8 4BA,"[51 Kensington Church Street, London W8 4BA, U...",London,4.5,british,££,236
37,Pizza Union,,E1 7HW,"[25 Sandy's Row, Corner of Middlesex Street, S...",London,4.5,pizza,£,81
39,Hawksmoor Spitalfields,+442074264850,E1 6BJ,"[157a Commercial Street, London E1 6BJ, United...",London,4.5,steak,£££,169
40,The Pig and Butcher,+442072268304,N1 0QD,"[80 Liverpool Road, London N1 0QD, United King...",London,4.5,british,££,93
42,Savoir Faire,+442074360707,WC1A 1EP,"[42 New Oxford Street, London WC1A 1EP, United...",London,4.5,french,££,187
43,Big Apple Hot Dogs,+442035925526,N1 0SQ,"[Cole & Sons, 170 Caledonian Rd, Kings Cross, ...",London,4.5,hotdog,££,47
44,Burger & Lobster,+442074091699,W1J 7EF,"[29 Clarges Street, Mayfair W1J 7EF, United Ki...",Mayfair,4.5,tradamerican,£££,211
45,The Victoria,+442077241191,W2 2NH,"[10a Strathearn Place, Paddington W2 2NH, Unit...",Paddington,4.5,pubs,££,173
47,Hawksmoor,+442074063980,W1J 0AD,"[5A Air Street, London W1J 0AD, United Kingdom]",London,4.5,seafood,£££,139
48,Barrafina,+442074401456,WC2B 5RT,"[43 Drury Lane, Covent Garden, London WC2B 5RT...",London,4.5,spanish,££,52
26,The Harwood Arms,+442073861847,SW6 1QP,"[27 Walham Grove, Fulham, London SW6 1QP, Unit...",London,4.5,gastropubs,£££,116
25,The Barbary,,WC2H 9DP,"[16 Neal's Yard, Seven Dials, London WC2H 9DP,...",London,4.5,mideastern,£££,50
24,Dishoom - Kensington,+442074209325,W8 5SE,"[4 Derry Street, Kensington W8 5SE, United Kin...",Kensington,4.5,indpak,££,77
11,Dishoom,+442074209324,E2 7JE,"[7 Boundary Street, London E2 7JE, United King...",London,4.5,indpak,££,413
2,Dishoom,+442074209322,W1B 5QP,"[22 Kingly Street, London W1B 5QP, United King...",London,4.5,indpak,££,433
3,Bailey's Fish and Chips,+442073852021,SW6 7EQ,"[115 Dawes Road, Fulham, London SW6 7EQ, Unite...",London,4.5,fishnchips,£,119
5,Dishoom,+442074209320,WC2H 9FB,"[12 Upper Saint Martin's Lane, London WC2H 9FB...",London,4.5,indpak,££,1601
6,Dishoom,+442074209321,N1C 4AB,"[5 Stable Street, London N1C 4AB, United Kingdom]",London,4.5,indpak,££,325
7,Regency Café,+442078216596,SW1P 4BY,"[17-19 Regency Street, London SW1P 4BY, United...",London,4.5,coffee,£,367
8,The Ledbury,+442077929090,W11 2AQ,"[127 Ledbury Road, London W11 2AQ, United King...",London,4.5,modern_european,££££,161
9,Flat Iron,+442030194212,WC2E 8QH,"[17-18 Henrietta Street, Covent Garden WC2E 8Q...",Covent Garden,4.5,steak,££,160
10,The Palomar Restaurant,+442074398777,W1D 6DN,"[34 Rupert Street, London W1D 6DN, United King...",London,4.5,mideastern,£££,91
23,Orjowan Lebanese Cuisine,+442073703074,SW5 0RR,"[6 Kenway Road, Earl's Court, London SW5 0RR, ...",London,4.5,mideastern,££,88
49,Petrus,+442075921609,SW1X 8EA,"[1 Kinnerton Street, Knightsbridge, London SW1...",London,4.5,french,££££,101
12,Hawksmoor Seven Dials,+442074209390,WC2H 9JG,"[11 Langley Street, London WC2H 9JG, United Ki...",London,4.5,british,£££,320
13,Restaurant Gordon Ramsay,+442073524441,SW3 4HP,"[68 Royal Hospital Road, London SW3 4HP, Unite...",London,4.5,french,££££,192
14,Padella,,SE1 1TQ,"[6 Southwark Street, London SE1 1TQ, United Ki...",London,4.5,italian,££,155
15,Dinner by Heston Blumenthal,+442072013833,SW1X 7LA,"[66 Knightsbridge, Mandarin Oriental at Hyde P...",London,4.5,british,££££,275
17,Flat Iron,,W1F 9RW,"[17 Beak Street, Soho, London W1F 9RW, United ...",London,4.5,steak,££,338
18,Friends of Ours,+442076865525,N1 6BU,"[61 Pitfield Street, London N1 6BU, United Kin...",London,4.5,cafes,££,87
19,Homeslice Neal's Yard,+442031517488,WC2H 9DP,"[13 Neal's Yard, Covent Garden, London WC2H 9D...",London,4.5,pizza,££,210
21,E Pellicci,+442077394873,E2 0AG,"[332 Bethnal Green Road, London E2 0AG, United...",London,4.5,italian,£,80
22,Honest Burgers,+442036099524,W1F 0EF,"[4A Meard Street, London W1F 0EF, United Kingdom]",London,4.5,burgers,££,259
41,St John Bar and Restaurant,+442072510848,EC1M 4AY,"[26 St John Street, London EC1M 4AY, United Ki...",London,4.0,british,£££,284
46,NOPI,+442074949584,W1B 5NE,"[21-22 Warwick Street, London W1B 5NE, United ...",London,4.0,mediterranean,£££,254
38,Mother Mash,+442074949644,W1F 7QZ,"[26 Ganton Street, London W1F 7QZ, United King...",London,4.0,british,££,414

In [22]:
#Save to a CSV all data retrieved
df_sort_ld.to_csv("London.csv", sep=',',index=False)
#df_ld.to_csv("London.csv", sep=',',index=False)

# 4) Paris

In [23]:
# Perform API Calls - test with one restaurant 
params_ps = {'term':'restaurant',
             'location':'Paris', 
             'sort_by': 'rating',  
             'limit':50}

In [24]:
request=requests.get(url, params=params_ps, headers=headers)
print('The status code is {}'.format(request.status_code))

The status code is 200

In [25]:
#Convert the data into a JSON object
parsed_ps = json.loads(request.text)
paris = parsed_ps["businesses"]

In [26]:
#“businesses” is a list, enclosed by a square brackets.
# extract businesses first into a Python list and then loop over the businesses in the list.
# count = 1
name = []
phone_number = []
postal_code =[]
address = []
city = []
rating = []
category = []
cost = []
review_count = []
 

for business in paris:
    #print("Number:", count)
    #print("Name:", business["name"])
    #print("Address:", " ".join(business["location"]["display_address"]))
    #print("City:", " ".join(business["location"]["city"]))
    #print("Rating:", business["rating"])
    #print("Category:", business["categories"][0].get('alias'))
        
    #if 'price' in business:
    #    print("Cost:", business["price"])
    #
    #print("\n")
    #print("Review Count:", business["review_count"])
    
    name.append(business["name"])
    phone_number.append(business["phone"])        
    postal_code.append(business["location"]["zip_code"])
    address.append(business["location"]["display_address"])
    city.append(business["location"]["city"])
    rating.append(business["rating"])
    category.append(business["categories"][0].get('alias'))
    
    
    if 'price' in business:
        cost.append(business["price"])
    else:
        cost.append("")
    review_count.append(business["review_count"])

    # count = count+1

In [27]:
#Display dataframe
#Display the DataFrame
df_ps = pd.DataFrame(data={"name": name, "phone_number": phone_number,"postal_code": postal_code, "address": address, "city": city, "rating":
                       rating, "category": category, "cost": cost, "review_Count": review_count})

df_sort_ps = df_ps.sort_values(by=['rating'], ascending=False)
df_sort_ps

,name,phone_number,postal_code,address,city,rating,category,cost,review_Count
31,Reed - Restaurant,+33145558840,75007,"[11 bis rue Amelie, 75007 Paris, France]",Paris,5.0,french,€€€,48
33,Bar Italia Brasserie,+33183972585,75009,"[22 rue Moncey, 75009 Paris, France]",Paris,5.0,italian,€€€,41
41,L'Estrapade,+33143257258,75005,"[15 rue de l'Estrapade, 75005 Paris, France]",Paris,5.0,french,€€€,42
14,La Vache et le Cuisinier,+33142622215,75018,"[18 rue des Trois Frères, 75018 Paris, France]",Paris,5.0,french,€€€,58
0,Le Potager du Père Thierry,+33153282620,75018,"[16 rue des Trois Frères, 75018 Paris, France]",Paris,4.5,french,€€,392
37,Le Jardin d'en Face,+33153280075,75018,"[29 rue des Trois Frères, 75018 Paris, France]",Paris,4.5,french,€€,82
28,La Cordonnerie,+33142601742,75001,"[20 rue Saint Roch, 75001 Paris, France]",Paris,4.5,french,€€€,74
29,Le Temps des Cerises,+33142720863,75004,"[31 rue de la Cerisaie, 75004 Paris, France]",Paris,4.5,bistros,€€,304
30,The Hardware Société,+33142516903,75018,"[10 rue Lamarck, 75018 Paris, France]",Paris,4.5,coffee,€€,134
32,Les Papilles,+33143252079,75005,"[30 rue Gay-Lussac, 75005 Paris, France]",Paris,4.5,wine_bars,€€€,230
34,La Jacobine,+33146341595,75006,"[59-61 rue Saint-André des Arts, 75006 Paris, ...",Paris,4.5,tea,€€€,247
35,L'Alsacien,+33142776422,75004,"[6 rue Saint-Bon, 75004 Paris, France]",Paris,4.5,beerbar,€€,61
36,Matamata Coffee Bar,+33171394458,75002,"[58 rue d'Argout, 75002 Paris, France]",Paris,4.5,coffee,€,75
38,Sacrée Fleur,+33142516618,75018,"[50 rue Clignancourt, 75018 Paris, France]",Paris,4.5,french,€€€,87
26,L'As du Fallafel,+33148876360,75004,"[34 rue des Rosiers, 75004 Paris, France]",Paris,4.5,kosher,€,1658
39,Pizzeria Babalou,+33142513732,75018,"[4 rue Lamarck, 75018 Paris, France]",Paris,4.5,italian,€€,155
40,Crêperie le Crépuscule,+33180061432,75007,"[18 rue Amélie, 75007 Paris, France]",Paris,4.5,creperies,€€,62
42,Les Antiquaires,+33142610836,75007,"[13 rue du Bac, 75007 Paris, France]",Paris,4.5,french,€€,242
43,Miznon,+33142748358,75004,"[22 rue des Ecouffes, 75004 Paris, France]",Paris,4.5,kosher,€€,145
44,L'Ardoise Gourmande,+33148784003,75010,"[12 rue de Belzunce, 75010 Paris, France]",Paris,4.5,french,€€,81
45,Banh Mi,+33148049890,75003,"[81 rue de Turbigo, 75003 Paris, France]",Paris,4.5,vietnamese,€,148
46,La Cave Gourmande,+33146061034,75018,"[96 rue des Martyrs, 75018 Paris, France]",Paris,4.5,french,€€,282
47,Au Pied du Sacré Coeur,+33146061526,75018,"[85 rue Lamarck, 75018 Paris, France]",Paris,4.5,french,€€,159
48,Verjus,+33142975440,75001,"[52 rue de Richelieu, 75001 Paris, France]",Paris,4.5,modern_european,€€€€,137
27,Galette Café,+33142602204,75007,"[2 rue de l'Université, 75007 Paris, France]",Paris,4.5,creperies,€€,98
25,Chez le Libanais,+33140460739,75006,"[35 rue Saint-André-des-Arts, 75006 Paris, Fra...",Paris,4.5,lebanese,€,164
1,La Coïncidence,+33147559644,75116,"[15 rue Mesnil, 75116 Paris, France]",Paris,4.5,french,€€,417
24,Soul Kitchen,+33171379995,75018,"[33 rue Lamarck, 75018 Paris, France]",Paris,4.5,coffee,€€,129
2,Le Comptoir de la Gastronomie,+33142333132,75001,"[34 rue Montmartre, 75001 Paris, France]",Paris,4.5,french,€€,872
3,Le Volant Basque,+33145752767,75015,"[13 rue Béatrix Dussane, 75015 Paris, France]",Paris,4.5,basque,€€,201
4,Holybelly,+33182280080,75010,"[5 rue Lucien Sampaix, 75010 Paris, France]",Paris,4.5,breakfast_brunch,€€,155
5,Fraîche,+33140375423,75010,"[8 rue Vicq d'Azir, 75010 Paris, France]",Paris,4.5,french,€€€,99
6,Le Cinq,+33149527154,75008,"[31 avenue George V, 75008 Paris, France]",Paris,4.5,french,€€€€,122
7,Pizza Julia,+33177196875,75012,"[43 rue de Charenton, 75012 Paris, France]",Paris,4.5,pizza,€,126
8,Le Bistrot des Augustins,+33143540441,75006,"[39 quai des Grands Augustins, 75006 Paris, Fr...",Paris,4.5,bistros,€€,322
9,Chez Alain Miam Miam,+33689865963,75003,"[26 rue Charlot, 75003 Paris, France]",Paris,4.5,creperies,€,132
10,L'Avant Comptoir,+33142384755,75006,"[3 carrefour de l'Odéon, 75006 Paris, France]",Paris,4.5,tapas,€€,576
11,Baguett's Café,+33954830486,75001,"[33 rue de Richelieu, 75001 Paris, France]",Paris,4.5,cafes,€€,161
12,L'Epicure,+33153434340,75008,"[112 rue du Faubourg Saint-Honoré, 75008 Paris...",Paris,4.5,french,€€€€,150
13,Le Hide,+33145741581,75017,"[10 Rue Gén Lanrezac, 75017 Paris, France]",Paris,4.5,french,€€€,193
15,Sanukiya,+33142605261,75001,"[9 rue d'Argenteuil, 75001 Paris, France]",Paris,4.5,japanese,€€,305
16,La Droguerie du Marais,,75004,"[56 rue des Rosiers, 75004 Paris, France]",Paris,4.5,creperies,€,176
17,Le Bistro du Périgord,+33143296749,75005,"[71 rue Saint-Jacques, 75005 Paris, France]",Paris,4.5,bistros,€€€,332
18,Le Petit Canard,+33149700795,75009,"[19 rue Henri Monnier, 75009 Paris, France]",Paris,4.5,french,€€,163
19,Chez Mademoiselle,+33142721416,75004,"[16 rue Charlemagne, 75004 Paris, France]",Paris,4.5,french,€€€,88
20,Crêperie Brocéliande,+33142233134,75018,"[15 rue des Trois Frères, 75018 Paris, France]",Paris,4.5,creperies,€€,116
21,Al Caratello,+33142622423,75018,"[5 rue Audran, 75018 Paris, France]",Paris,4.5,italian,€€,160
22,Le Bistrot des Campagnes,+33140479127,75014,"[6 rue Léopold Robert, 75014 Paris, France]",Paris,4.5,bistros,€€,117
23,Little Breizh,+33143546074,75006,"[11 rue Grégoire de Tours, 75006 Paris, France]",Paris,4.5,creperies,€€,188
49,Chez Gabrielle,+33143802301,75017,"[7 rue de l'Etoile, 75017 Paris, France]",Paris,4.5,french,€€€,59

In [28]:
#Save to a CSV all data retrieved
df_sort_ps.to_csv("Paris.csv", sep=',',index=False)
#df_ps.to_csv("Paris.csv", sep=',',index=False)

# 5) Tokyo

In [29]:
# Perform API Calls - test with one restaurant 
params_tk = {'term':'restaurant',
             'location':'Tokyo', 
             'sort_by': 'rating',    
             'limit':'50'}

In [30]:
request=requests.get(url, params=params_tk, headers=headers)
print('The status code is {}'.format(request.status_code))

The status code is 200

In [31]:
#Convert the data into a JSON object
parsed_tk = json.loads(request.text)
tokyo = parsed_tk["businesses"]

In [32]:
#“businesses” is a list, enclosed by a square brackets.
# extract businesses first into a Python list and then loop over the businesses in the list.
# count = 1
name = []
phone_number = []
postal_code =[]
address = []
city = []
rating = []
category = []
cost = []
review_count = []
 

for business in tokyo:
    #print("Number:", count)
    #print("Name:", business["name"])
    #print("Address:", " ".join(business["location"]["display_address"]))
    #print("City:", " ".join(business["location"]["city"]))
    #print("Rating:", business["rating"])
    #print("Category:", business["categories"][0].get('alias'))
        
    #if 'price' in business:
    #    print("Cost:", business["price"])
    #
    #print("\n")
    #print("Review Count:", business["review_count"])
    
    name.append(business["name"])
    phone_number.append(business["phone"])        
    postal_code.append(business["location"]["zip_code"])
    address.append(business["location"]["display_address"])
    city.append(business["location"]["city"])
    rating.append(business["rating"])
    category.append(business["categories"][0].get('alias'))
    
    
    if 'price' in business:
        cost.append(business["price"])
    else:
        cost.append("")
    review_count.append(business["review_count"])

    # count = count+1

In [33]:
#Display the DataFrame
#Display the DataFrame
df_tk = pd.DataFrame(data={"name": name, "phone_number": phone_number,"postal_code": postal_code, "address": address, "city": city, "rating":
                       rating, "category": category, "cost": cost, "review_Count": review_count})

df_sort_tk = df_tk.sort_values(by=['rating'], ascending=False)
df_sort_tk

,name,phone_number,postal_code,address,city,rating,category,cost,review_Count
31,Ibuki,+81353233552,160-0023,"[西新宿1-16-8, 河野ビル別館2F, Shinjuku, 東京都 〒160-0023,...",Shinjuku,5.0,sukiyaki,,41
22,Ichiran Shibuya Spainzaka,+81334640787,150-0042,"[宇田川町13-7, コヤスワンB1F, Shibuya, 東京都 〒150-0042, J...",Shibuya,5.0,ramen,￥,51
40,Gomei,+81368917711,104-0061,"[銀座6-4-18-B1, Chūō, 東京都 〒104-0061, Japan]",Chūō,5.0,kaiseki,￥￥￥￥,25
3,Sushisho Masa,+81334999178,106-0031,"[西麻布4丁目1-15, セブン西麻布, Minato, 東京都 〒106-0031, Ja...",Minato,5.0,sushi,￥￥￥￥,49
4,Uogashi Nihon Ichi Shinjuku Nishiguchi,+81333491739,160-0023,"[西新宿1-12, 河西ビル1F, Shinjuku, 東京都 〒160-0023, Japan]",Shinjuku,5.0,sushi,￥,90
5,Hakushu,+81334610546,150-0031,"[桜丘町17-10, MCD Building 1F, Shibuya, 東京都 〒150-...",Shibuya,5.0,steak,￥￥￥,85
16,Sapporo DOMINICA Ginza,+81332311347,104-0031,"[京橋3-4-1, ＴＭ銀座ビル 2F, Chūō, 東京都 〒104-0031, Japan]",Chūō,5.0,japacurry,￥,56
46,Manten Sushi,+81362699100,100-0005,"[丸の内2-6-1, 丸の内ブリックスクエアB1F, Chiyoda, 東京都 〒100-0...",Chiyoda,5.0,sushi,￥￥￥,34
1,Gyukatsu MOTOMURA Tokyo Eki Yaesuguchi,+81332310337,103-0028,"[八重洲1-6-14, Chūō, 東京都 〒103-0028, Japan]",Chūō,5.0,japanese,￥￥,80
37,Tokyo Shiba Tofuya Ukai,+81334361028,105-0011,"[芝公園4-4-13, Minato, 東京都 〒105-0011, Japan]",Minato,5.0,kaiseki,￥￥￥,36
10,AKIBA FUKUROU,+818034003511,101-0022,"[神田練塀町67, Chiyoda, 東京都 〒101-0022, Japan]",Chiyoda,5.0,themedcafes,￥,66
11,Gyukatsu Motomura Shinjuku,+81333540171,160-0022,"[新宿3-32-2, モトビル地下1F, Shinjuku, 東京都 〒160-0022, ...",Shinjuku,5.0,tempura,￥￥,72
43,Umai Sushi Kan Akasaka,+81335606711,107-0052,"[赤坂3丁目13-10, Minato, 東京都 〒107-0052, Japan]",Minato,5.0,sushi,￥￥,28
15,Abura Soba Tōkyō Aburagumi Sōhonten,+81355716011,107-0052,"[赤坂3-10-20, Minato, 東京都 〒107-0052, Japan]",Minato,5.0,ramen,￥,55
34,511,+81366850511,135-0063,"[赤坂4-3-28, ディアプラザ赤坂B1, Minato, 東京都 〒135-0063, ...",Minato,4.5,steak,￥￥￥￥,87
35,Umegaoka Sushinomidori Sōhonten Shibuya,+81354580002,150-0043,"[道玄坂1-12-3, 4Ｆ, Shibuya, 東京都 〒150-0043, Japan]",Shibuya,4.5,sushi,￥￥,123
33,Afuri Ebisu,+81357950750,150-0013,"[恵比寿1-1-7, Shibuya, 東京都 〒150-0013, Japan]",Shibuya,4.5,ramen,￥,129
32,Rokurinsha,+81332860166,100-0005,"[丸の内1-9-1, B1F, Chiyoda, 東京都 〒100-0005, Japan]",Chiyoda,4.5,ramen,￥,219
36,Fukki,+81364029011,105-0012,"[芝大門2-1-1, Minato, 東京都 〒105-0012, Japan]",Minato,4.5,ramen,￥,43
0,Ichiran Shinjuku Chuo Higashiguchi,+81332255518,160-0022,"[新宿3-34-11, ピースビルB1F, Shinjuku, 東京都 〒160-0022,...",Shinjuku,4.5,ramen,￥,406
38,AIN SOPH. Ripple,+81363803205,160-0021,"[歌舞伎町2-46-8, 日章ビル 1F, Shinjuku, 東京都 〒160-0021,...",Shinjuku,4.5,vegan,￥,46
39,Tonki Meguro,+81334919928,153-0064,"[下目黒1-1-2, Meguro, 東京都 〒153-0064, Japan]",Meguro,4.5,tonkatsu,￥,76
30,Marugo,+81332556595,101-0021,"[外神田1丁目8-14, Chiyoda, 東京都 〒101-0021, Japan]",Chiyoda,4.5,tonkatsu,￥￥,50
42,Imakatsu Roppongi Honten,+81334081029,106-0032,"[六本木4-12-5, フェニキアルクソス ス 1F, Minato, 東京都 〒106-0...",Minato,4.5,tonkatsu,￥￥,41
44,SUSHIZANMAI Honten,+81335411117,104-0045,"[築地4-11-9, Chūō, 東京都 〒104-0045, Japan]",Chūō,4.5,sushi,￥￥,121
45,Reissue,+81357853144,150-0001,"[神宮前3-25-7, 丹治ビル 2F, Shibuya, 東京都 〒150-0001, J...",Shibuya,4.5,coffee,￥,92
47,KYUSHU JANGARA Omotesando 2F,+81334045572,150-0001,"[神宮前1-13-21, Shibuya, 東京都 〒150-0001, Japan]",Shibuya,4.5,ramen,￥,76
48,Nabezo Shinjuku 3 Chome,+81353634629,160-0022,"[新宿3丁目30-11, 新宿高野第2ビル8F, Shinjuku, 東京都 〒160-00...",Shinjuku,4.5,sukiyaki,￥￥,86
41,Ichiran Ikebukuro,+81339890871,170-0013,"[東池袋1丁目39-11, サニーサイドビル102, Toshima, 東京都 〒170-0...",Toshima,4.5,ramen,￥,44
25,Tonkatsu Maisen Aoyama Honten,+81120428485,150-0001,"[神宮前4-8-5, Shibuya, 東京都 〒150-0001, Japan]",Shibuya,4.5,tonkatsu,￥￥,161
29,Narisawa,+81357850799,107-0062,"[南青山2-6-15, Minato, 東京都 〒107-0062, Japan]",Minato,4.5,asianfusion,￥￥￥￥,52
28,Uogashi Nihonichi Tachigui Sushi SHIBUYA CENTE...,+81357285451,150-0042,"[宇田川町25-6, Shibuya, 東京都 〒150-0042, Japan]",Shibuya,4.5,sushi,￥￥,54
2,Ichiran Shibuya,+81334633667,150-0041,"[神南1-22-7, 岩本ビルB1F, Shibuya, 東京都 〒150-0041, Ja...",Shibuya,4.5,ramen,￥,529
6,Gyūkatsu Motomura Shibuya,+81337973735,979-1308,"[渋谷3-18-10, 大野ビル2号館 B1F, Shibuya, 東京都 〒979-130...",Shibuya,4.5,tempura,￥,101
7,Ippudo Ginza,+81335471010,104-0061,"[銀座4-10-3, セントラルビル 1F, Chūō, 東京都 〒104-0061, Ja...",Chūō,4.5,ramen,￥,179
8,T's Tantan Tokyo Station Keiyo Street,+81332188040,100-0005,"[丸の内1-9-1, 改札内 京葉ストリート, Chiyoda, 東京都 〒100-0005...",Chiyoda,4.5,vegan,￥,148
9,Kyubey Ginza,+81335716523,104-0061,"[銀座8-7-6, 銀座本店, Chūō, 東京都 〒104-0061, Japan]",Chūō,4.5,sushi,￥￥￥￥,106
12,Karashibi Miso Ramen Kikanbo,+81332562960,101-0044,"[鍛冶町2-10-10, Chiyoda, 東京都 〒101-0044, Japan]",Chiyoda,4.5,ramen,￥,84
13,Udon Shin,+81362767816,151-0053,"[代々木2-20-16, 相馬ビル 1F, Shibuya, 東京都 〒151-0053, ...",Shibuya,4.5,udon,￥,145
14,Fuunji,+81364138480,151-0053,"[代々木2-14-3, 北斗第一ビルB1F, Shibuya, 東京都 〒151-0053,...",Shibuya,4.5,ramen,￥,198
17,Fūryū Okonomiyaki Sometarō,+81338449502,111-0035,"[西浅草2-2-2, Taitō, 東京都 〒111-0035, Japan]",Taitō,4.5,okonomiyaki,￥,86
18,Jirōmaru Shinjuku Honten,+81363803292,160-0021,"[歌舞伎町1-26-3, かぶきビル 1F, Shinjuku, 東京都 〒160-0021...",Shinjuku,4.5,yakiniku,￥￥,182
19,Japanese Soba Noodles Tsuta,+81339431007,170-0002,"[巣鴨1-14-1, Plateau-Saka 1F, Toshima, 東京都 〒170-...",Toshima,4.5,ramen,￥,168
20,Sukiyabashi Jiro Roppongi Hills,+81354136626,106-0032,"[六本木6-10-1, 六本木ヒルズ けやき坂通り 3F, Minato, 東京都 〒106...",Minato,4.5,sushi,￥￥￥￥,86
21,Tatsunoya,+81363040899,160-0023,"[西新宿7-4-5, 富士野ビル 1F, Shinjuku, 東京都 〒160-0023, ...",Shinjuku,4.5,ramen,￥,60
23,Turret COFFEE,+818033448819,104-0045,"[築地2-12-6, SK東銀座ビル 1F, Chūō, 東京都 〒104-0045, Ja...",Chūō,4.5,cafes,￥,86
24,Mutekiya,+81339827656,171-0022,"[南池袋1-17-1, 崎本ビル1F, Toshima, 東京都 〒171-0022, Ja...",Toshima,4.5,ramen,￥,87
26,Kaiten Zushi Katsu Seibu Shibuya,+81357284282,150-0042,"[宇田川町21-1, 8F, Shibuya, 東京都 〒150-0042, Japan]",Shibuya,4.5,conveyorsushi,￥￥,90
27,NAKIRYU,+81363041811,170-0005,"[南大塚2-34-4, SKY南大塚 1F, Toshima, 東京都 〒170-0005,...",Toshima,4.5,ramen,￥,82
49,MENYA MUSASHI SHINJUKU Honten,+81333634634,160-0023,"[西新宿7-2-6, K-1ビル1F, Shinjuku, 東京都 〒160-0023, J...",Shinjuku,4.5,ramen,￥,92

In [34]:
#Save to a CSV all data retrieved
df_sort_tk.to_csv("Tokyo.csv", sep=',',index=False)
#df_tk.to_csv("Tokyo.csv", sep=',',index=False)

# Read Into Database

In [ ]:
import pymysql
pymysql.install_as_MySQLdb()

from sqlalchemy import create_engine
#engine = create_engine("mysql://USER:PASSWORD@HOST/DATABASE")
engine = create_engine("mysql://root:root123@localhost/restaurant_review")

In [ ]:
df_sort_ny.to_sql(
                name='yelp',
                con=engine,
                index= False,
                if_exists="append"
                 )

In [ ]:
df_sort_ld.to_sql(
                name='yelp',
                con=engine,
                index= False,
                if_exists="append"
                 )

In [ ]:
df_sort_ps.to_sql(
                name='yelp',
                con=engine,
                index=False,
                if_exists="append"
                 )

In [ ]:
df_sort_tk.to_sql(
                name='yelp',
                con=engine,
                index=False,
                if_exists="append"
                 )